### ISSUE TITLE
Couldn't execute the script

### ISSUE THREAD

**Issue by davidrosa1810** [waldner/openvpn-ldap#1]
I used the .bash script and changed some variables accordingly to my needs. When i try to connect it does prompt me with the username/password request but it always says wrong credentials. I'll be putting my client and server logs in here, as well as their configs. I saw on the server config that "could not execute external program", i don't know how to solve this, please help.
[Uranus.txt](https://github.com/waldner/openvpn-ldap/files/4544835/Uranus.txt)

[client.txt](https://github.com/waldner/openvpn-ldap/files/4544843/client.txt)

[server.log](https://github.com/waldner/openvpn-ldap/files/4544824/server.log)

[Client.log](https://github.com/waldner/openvpn-ldap/files/4544746/Client.log)

**Comment by waldner** [comment]
As explained, if you call the script using `via-env` you have to use `script-security 3` in the server configuration. You have it set to 2 currently.
